/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jni_Demo */

#ifndef _Included_com_jni_Demo
#define _Included_com_jni_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_Demo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_Demo_sayHello
  (JNIEnv *, jobject);
 
#ifdef __cplusplus
}
#endif
#endif
